# GitHub Pages configuration file

title: Unit Project 3.1 - GitHub Pages Portfolio

description: CRCP 3320 Unit Project 3.1 - GitHub Pages Portfolio Assignment

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme