# GitHub Pages configuration file

title: Unit Project 3.1 - GitHub Pages Portfolio

description: CRCP 3320 Unit Project 3.1 - GitHub Pages Portfolio Assignment due on October 20, 2024 by 11:59pm

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme